name: Build Web

on: 
    push:
        branches:
            - lab7
    pull_request:
        branches:
            - lab7

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2
            - run: flutter pub get

            - run: flutter test test/main_test.dart

            - run: flutter analyze  lib/templates/lab7/

            - run: flutter build web --release lib/templates/lab7/main.dart

            - uses: bluefireteam/flutter-gh-pages@v7
              with:
                baseHref: /Sum24FlutterCourse/
                customArgs: "lib/templates/lab7/main.dart"
    main:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
            with:
                channel: stable
        - run: flutter build windows lib/templates/lab7/main.dart


